name:                unsafePerformIO
version:             0.1.0.0
github:              "wilfreddenton/unsafePerformIO"
license:             BSD3
author:              "Wilfred Denton"
maintainer:          "dentonw3@gmail.com"
copyright:           "2018 Wilfred Denton"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wilfreddenton/unsafePerformIO#readme>

ghc-options:
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wall
- -Werror

default-extensions:
- NoImplicitPrelude
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-casing
- base16-bytestring
- bytestring
- clock
- containers
- cryptonite
- directory
- h-gpgme
- http-types
- katip
- lens
- lucid
- memory
- mmark
- optparse-applicative
- protolude
- servant
- servant-lucid
- servant-server
- sqlite-simple
- template-haskell
- text
- time
- wai
- wai-middleware-throttle
- warp

library:
  source-dirs: src

executables:
  unsafe-perform-io:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unsafePerformIO

tests:
  unsafe-perform-io-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unsafePerformIO
