name:                haskell-starter-pack
version:             0.1.0.0
github:              "githubuser/haskell-starter-pack"
license:             BSD3
author:              "Wilfred Denton"
maintainer:          "dentonw3@gmail.com"
copyright:           "2018 Wilfred Denton"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-starter-pack#readme>

ghc-options:
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wall
- -Werror

default-extensions:
- NoImplicitPrelude
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- aeson
- katip
- lens
- optparse-applicative
- protolude
- servant
- servant-server
- time
- wai
- warp

library:
  source-dirs: src

executables:
  haskell-starter-pack:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-starter-pack

tests:
  haskell-starter-pack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-starter-pack
